FROM golang:1.21-alpine

# Install build dependencies
RUN apk add --no-cache git protobuf

# Install protoc-gen-go and protoc-gen-go-grpc
RUN go install google.golang.org/protobuf/cmd/protoc-gen-go@v1.31.0 && \
    go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@v1.3.0

WORKDIR /app

COPY go.mod ./
COPY . .

RUN mkdir -p pb
WORKDIR /app/proto
RUN protoc --go_out=paths=source_relative:../pb --go-grpc_out=paths=source_relative:../pb tracker.proto

CMD ["ls", "-R", "/app/pb"]
